# Generated by Django 4.0.8 on 2022-10-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('oferta', models.CharField(max_length=150)),
                ('cueanexo', models.CharField(max_length=9)),
            ],
        ),
    ]
