# Generated by Django 4.0.8 on 2022-10-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('oferta', models.CharField(max_length=50)),
                ('school_user', models.ForeignKey(help_text='ID de usuario escuela que es el CUEANEXO', on_delete=django.db.models.deletion.CASCADE, to='users.schooluser')),
            ],
        ),
    ]
