# Generated by Django 4.0.8 on 2023-02-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoOfertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueanexo', models.CharField(blank=True, max_length=250, null=True)),
                ('anexo', models.CharField(blank=True, max_length=250, null=True)),
                ('oferta', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_est', models.CharField(blank=True, max_length=250, null=True)),
                ('cue', models.ForeignKey(help_text='Cue asociado a la oferta', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
