# Generated by Django 4.0.8 on 2023-02-04 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoofertas',
            name='cue',
            field=models.ForeignKey(db_column='cue', help_text='Cue asociado a la oferta', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
