# Generated by Django 4.0.8 on 2023-02-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_alter_anexoofertas_cue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueanexo', models.CharField(blank=True, max_length=250, null=True)),
                ('anexo', models.CharField(blank=True, max_length=250, null=True)),
                ('oferta', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_est', models.CharField(blank=True, max_length=250, null=True)),
                ('cue', models.ForeignKey(db_column='cue', help_text='Cue asociado a la oferta', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.DeleteModel(
            name='AnexoOfertas',
        ),
    ]
