# Generated by Django 4.0.8 on 2023-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_offer_delete_anexoofertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DechDesempenio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cueanexo', models.TextField(max_length=100)),
                ('desempenio', models.BigIntegerField(default=0)),
                ('punto', models.BigIntegerField(default=0)),
                ('promedio', models.BigIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
