# Generated by Django 4.0.8 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_dechdesempenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DechTotalScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cueanexo', models.CharField(max_length=100)),
                ('puntaje_m', models.BigIntegerField(default=0)),
                ('puntaje_l', models.BigIntegerField(default=0)),
                ('puntaje_cn', models.BigIntegerField(default=0)),
                ('puntaje_cs', models.BigIntegerField(default=0)),
                ('pt_m', models.BigIntegerField(default=0)),
                ('pt_l', models.BigIntegerField(default=0)),
                ('pt_cn', models.BigIntegerField(default=0)),
                ('pt_cs', models.BigIntegerField(default=0)),
                ('puntaje_promedio', models.BigIntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
