# Generated by Django 4.0.8 on 2023-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_dechtotalscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupacionCueanexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
