# Generated by Django 4.0.8 on 2022-10-26 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('cueanexo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password_ra', models.CharField(help_text='Password que utiliza en RA', max_length=50)),
                ('user_ra', models.CharField(help_text='Password que utiliza en RA', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpDeskUser',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
