# Generated by Django 4.0.8 on 2022-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cueanexo',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
