# Generated by Django 4.0.8 on 2023-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_ra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ra',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password que utiliza en RA', max_length=50),
        ),
    ]
