# Generated by Django 4.0.8 on 2023-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_password_ra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_pass',
            field=models.CharField(default=None, help_text='Password que utiliza en RA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
