# Generated by Django 4.0.8 on 2023-02-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_failed_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_pass',
        ),
        migrations.AddField(
            model_name='user',
            name='set_password',
            field=models.BooleanField(default=False),
        ),
    ]
