# Generated by Django 4.0.8 on 2023-02-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_random_pass_user_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='set_password',
            new_name='passwrod_entered',
        ),
    ]
