# Generated by Django 4.0.8 on 2023-02-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_set_password_user_passwrod_entered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrod_entered',
            new_name='password_entered',
        ),
    ]
